# Generated by Django 6.1 on 2026-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='Optional. Shown to guests as a From - To time range.', null=True),
        ),
    ]
