# Generated by Django 6.1 on 2026-10-08 09:16

import common.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.validate_image_max_5mb]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='Optional. Shown to guests as a From - To time range. May be earlier than the start time for events that run past midnight.', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', '-event_date'], name='events_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='events_org_status_idx'),
        ),
    ]
