# Generated by Django 6.1 on 2026-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_cover_image_alter_event_event_end_time_and_more'),
        ('guests', '0004_guestcategory_guest_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'response_status'], name='guests_event_response_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'invitation_status'], name='guests_event_invite_idx'),
        ),
    ]
