# Generated by Django 6.1 on 2026-10-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobileotp',
            name='purpose',
            field=models.CharField(choices=[('VERIFY_MOBILE', 'Verify mobile number'), ('RESET_PASSWORD', 'Reset password')], default='VERIFY_MOBILE', max_length=20),
        ),
    ]
